### ISSUE TITLE
Save player's name

### ISSUE THREAD

**Issue by b123400** [alex-fok/minesweeper#8]
Save it somewhere and prefill the alias field, so that I don't have to type my name every time.

**Comment by alex-fok** [comment]
[272a94c](https://github.com/alex-fok/minesweeper/commit/272a94ce3c1aabf7ec673ffc3769c4440fbc43d6)

**Comment by b123400** [comment]
You can type #8 in the commit message, then it will be automatically referenced to this issue, so you don't have to paste the commit hash manually.

**Comment by alex-fok** [comment]
Didn't know that. Thanks!
